export type CountryCallingCodeOption = {
  iso2: string;
  country: string;
  callingCode: string; // includes leading "+"
};

function iso2ToFlagEmoji(iso2: string): string {
  const upper = iso2.trim().toUpperCase();
  if (upper.length !== 2) return "";
  const a = upper.charCodeAt(0);
  const b = upper.charCodeAt(1);
  const A = 65;
  const Z = 90;
  if (a < A || a > Z || b < A || b > Z) return "";
  const REGIONAL_INDICATOR_A = 0x1f1e6;
  return String.fromCodePoint(REGIONAL_INDICATOR_A + (a - A), REGIONAL_INDICATOR_A + (b - A));
}

export function formatCountryCallingCodeLabel(option: CountryCallingCodeOption): string {
  const flag = iso2ToFlagEmoji(option.iso2);
  const flagPrefix = flag ? `${flag} ` : "";
  return `${flagPrefix}${option.country} (${option.callingCode})`;
}

export function formatCountryCallingCodeCompactLabel(option: CountryCallingCodeOption): string {
  const flag = iso2ToFlagEmoji(option.iso2);
  const flagPrefix = flag ? `${flag} ` : "";
  return `${flagPrefix}${option.callingCode}`;
}

// Curated list covering virtually all ITU country calling codes.
// NOTE: Some territories share calling codes (e.g. NANP +1). We keep entries distinct by ISO2/country.
export const COUNTRY_CALLING_CODES: CountryCallingCodeOption[] = [
  { iso2: "US", country: "United States", callingCode: "+1" },
  { iso2: "CA", country: "Canada", callingCode: "+1" },
  { iso2: "AG", country: "Antigua and Barbuda", callingCode: "+1" },
  { iso2: "AI", country: "Anguilla", callingCode: "+1" },
  { iso2: "AS", country: "American Samoa", callingCode: "+1" },
  { iso2: "BB", country: "Barbados", callingCode: "+1" },
  { iso2: "BM", country: "Bermuda", callingCode: "+1" },
  { iso2: "BS", country: "Bahamas", callingCode: "+1" },
  { iso2: "DM", country: "Dominica", callingCode: "+1" },
  { iso2: "DO", country: "Dominican Republic", callingCode: "+1" },
  { iso2: "GD", country: "Grenada", callingCode: "+1" },
  { iso2: "GU", country: "Guam", callingCode: "+1" },
  { iso2: "JM", country: "Jamaica", callingCode: "+1" },
  { iso2: "KN", country: "Saint Kitts and Nevis", callingCode: "+1" },
  { iso2: "KY", country: "Cayman Islands", callingCode: "+1" },
  { iso2: "LC", country: "Saint Lucia", callingCode: "+1" },
  { iso2: "MP", country: "Northern Mariana Islands", callingCode: "+1" },
  { iso2: "MS", country: "Montserrat", callingCode: "+1" },
  { iso2: "PR", country: "Puerto Rico", callingCode: "+1" },
  { iso2: "SX", country: "Sint Maarten", callingCode: "+1" },
  { iso2: "TC", country: "Turks and Caicos Islands", callingCode: "+1" },
  { iso2: "TT", country: "Trinidad and Tobago", callingCode: "+1" },
  { iso2: "VC", country: "Saint Vincent and the Grenadines", callingCode: "+1" },
  { iso2: "VG", country: "British Virgin Islands", callingCode: "+1" },
  { iso2: "VI", country: "U.S. Virgin Islands", callingCode: "+1" },

  { iso2: "RU", country: "Russia", callingCode: "+7" },
  { iso2: "KZ", country: "Kazakhstan", callingCode: "+7" },

  { iso2: "EG", country: "Egypt", callingCode: "+20" },
  { iso2: "ZA", country: "South Africa", callingCode: "+27" },
  { iso2: "GR", country: "Greece", callingCode: "+30" },
  { iso2: "NL", country: "Netherlands", callingCode: "+31" },
  { iso2: "BE", country: "Belgium", callingCode: "+32" },
  { iso2: "FR", country: "France", callingCode: "+33" },
  { iso2: "ES", country: "Spain", callingCode: "+34" },
  { iso2: "HU", country: "Hungary", callingCode: "+36" },
  { iso2: "IT", country: "Italy", callingCode: "+39" },
  { iso2: "RO", country: "Romania", callingCode: "+40" },
  { iso2: "CH", country: "Switzerland", callingCode: "+41" },
  { iso2: "AT", country: "Austria", callingCode: "+43" },
  { iso2: "GB", country: "United Kingdom", callingCode: "+44" },
  { iso2: "DK", country: "Denmark", callingCode: "+45" },
  { iso2: "SE", country: "Sweden", callingCode: "+46" },
  { iso2: "NO", country: "Norway", callingCode: "+47" },
  { iso2: "PL", country: "Poland", callingCode: "+48" },
  { iso2: "DE", country: "Germany", callingCode: "+49" },

  { iso2: "PE", country: "Peru", callingCode: "+51" },
  { iso2: "MX", country: "Mexico", callingCode: "+52" },
  { iso2: "CU", country: "Cuba", callingCode: "+53" },
  { iso2: "AR", country: "Argentina", callingCode: "+54" },
  { iso2: "BR", country: "Brazil", callingCode: "+55" },
  { iso2: "CL", country: "Chile", callingCode: "+56" },
  { iso2: "CO", country: "Colombia", callingCode: "+57" },
  { iso2: "VE", country: "Venezuela", callingCode: "+58" },
  { iso2: "MY", country: "Malaysia", callingCode: "+60" },
  { iso2: "AU", country: "Australia", callingCode: "+61" },
  { iso2: "ID", country: "Indonesia", callingCode: "+62" },
  { iso2: "PH", country: "Philippines", callingCode: "+63" },
  { iso2: "NZ", country: "New Zealand", callingCode: "+64" },
  { iso2: "SG", country: "Singapore", callingCode: "+65" },
  { iso2: "TH", country: "Thailand", callingCode: "+66" },
  { iso2: "JP", country: "Japan", callingCode: "+81" },
  { iso2: "KR", country: "South Korea", callingCode: "+82" },
  { iso2: "VN", country: "Vietnam", callingCode: "+84" },
  { iso2: "CN", country: "China", callingCode: "+86" },
  { iso2: "TR", country: "Turkey", callingCode: "+90" },
  { iso2: "IN", country: "India", callingCode: "+91" },
  { iso2: "PK", country: "Pakistan", callingCode: "+92" },
  { iso2: "AF", country: "Afghanistan", callingCode: "+93" },
  { iso2: "LK", country: "Sri Lanka", callingCode: "+94" },
  { iso2: "MM", country: "Myanmar", callingCode: "+95" },
  { iso2: "IR", country: "Iran", callingCode: "+98" },
  { iso2: "SS", country: "South Sudan", callingCode: "+211" },
  { iso2: "MA", country: "Morocco", callingCode: "+212" },
  { iso2: "DZ", country: "Algeria", callingCode: "+213" },
  { iso2: "TN", country: "Tunisia", callingCode: "+216" },
  { iso2: "LY", country: "Libya", callingCode: "+218" },
  { iso2: "GM", country: "Gambia", callingCode: "+220" },
  { iso2: "SN", country: "Senegal", callingCode: "+221" },
  { iso2: "MR", country: "Mauritania", callingCode: "+222" },
  { iso2: "ML", country: "Mali", callingCode: "+223" },
  { iso2: "GN", country: "Guinea", callingCode: "+224" },
  { iso2: "CI", country: "Côte d’Ivoire", callingCode: "+225" },
  { iso2: "BF", country: "Burkina Faso", callingCode: "+226" },
  { iso2: "NE", country: "Niger", callingCode: "+227" },
  { iso2: "TG", country: "Togo", callingCode: "+228" },
  { iso2: "BJ", country: "Benin", callingCode: "+229" },
  { iso2: "MU", country: "Mauritius", callingCode: "+230" },
  { iso2: "LR", country: "Liberia", callingCode: "+231" },
  { iso2: "SL", country: "Sierra Leone", callingCode: "+232" },
  { iso2: "GH", country: "Ghana", callingCode: "+233" },
  { iso2: "NG", country: "Nigeria", callingCode: "+234" },
  { iso2: "TD", country: "Chad", callingCode: "+235" },
  { iso2: "CF", country: "Central African Republic", callingCode: "+236" },
  { iso2: "CM", country: "Cameroon", callingCode: "+237" },
  { iso2: "CV", country: "Cape Verde", callingCode: "+238" },
  { iso2: "ST", country: "São Tomé and Príncipe", callingCode: "+239" },
  { iso2: "GQ", country: "Equatorial Guinea", callingCode: "+240" },
  { iso2: "GA", country: "Gabon", callingCode: "+241" },
  { iso2: "CG", country: "Republic of the Congo", callingCode: "+242" },
  { iso2: "CD", country: "DR Congo", callingCode: "+243" },
  { iso2: "AO", country: "Angola", callingCode: "+244" },
  { iso2: "GW", country: "Guinea-Bissau", callingCode: "+245" },
  { iso2: "IO", country: "British Indian Ocean Territory", callingCode: "+246" },
  { iso2: "SC", country: "Seychelles", callingCode: "+248" },
  { iso2: "SD", country: "Sudan", callingCode: "+249" },
  { iso2: "RW", country: "Rwanda", callingCode: "+250" },
  { iso2: "ET", country: "Ethiopia", callingCode: "+251" },
  { iso2: "SO", country: "Somalia", callingCode: "+252" },
  { iso2: "DJ", country: "Djibouti", callingCode: "+253" },
  { iso2: "KE", country: "Kenya", callingCode: "+254" },
  { iso2: "TZ", country: "Tanzania", callingCode: "+255" },
  { iso2: "UG", country: "Uganda", callingCode: "+256" },
  { iso2: "BI", country: "Burundi", callingCode: "+257" },
  { iso2: "MZ", country: "Mozambique", callingCode: "+258" },
  { iso2: "ZM", country: "Zambia", callingCode: "+260" },
  { iso2: "MG", country: "Madagascar", callingCode: "+261" },
  { iso2: "RE", country: "Réunion", callingCode: "+262" },
  { iso2: "YT", country: "Mayotte", callingCode: "+262" },
  { iso2: "ZW", country: "Zimbabwe", callingCode: "+263" },
  { iso2: "NA", country: "Namibia", callingCode: "+264" },
  { iso2: "MW", country: "Malawi", callingCode: "+265" },
  { iso2: "LS", country: "Lesotho", callingCode: "+266" },
  { iso2: "BW", country: "Botswana", callingCode: "+267" },
  { iso2: "SZ", country: "Eswatini", callingCode: "+268" },
  { iso2: "KM", country: "Comoros", callingCode: "+269" },
  { iso2: "ER", country: "Eritrea", callingCode: "+291" },
  { iso2: "AW", country: "Aruba", callingCode: "+297" },
  { iso2: "FO", country: "Faroe Islands", callingCode: "+298" },
  { iso2: "GL", country: "Greenland", callingCode: "+299" },

  { iso2: "GI", country: "Gibraltar", callingCode: "+350" },
  { iso2: "PT", country: "Portugal", callingCode: "+351" },
  { iso2: "LU", country: "Luxembourg", callingCode: "+352" },
  { iso2: "IE", country: "Ireland", callingCode: "+353" },
  { iso2: "IS", country: "Iceland", callingCode: "+354" },
  { iso2: "AL", country: "Albania", callingCode: "+355" },
  { iso2: "MT", country: "Malta", callingCode: "+356" },
  { iso2: "CY", country: "Cyprus", callingCode: "+357" },
  { iso2: "FI", country: "Finland", callingCode: "+358" },
  { iso2: "AX", country: "Åland Islands", callingCode: "+358" },
  { iso2: "BG", country: "Bulgaria", callingCode: "+359" },
  { iso2: "LT", country: "Lithuania", callingCode: "+370" },
  { iso2: "LV", country: "Latvia", callingCode: "+371" },
  { iso2: "EE", country: "Estonia", callingCode: "+372" },
  { iso2: "MD", country: "Moldova", callingCode: "+373" },
  { iso2: "AM", country: "Armenia", callingCode: "+374" },
  { iso2: "BY", country: "Belarus", callingCode: "+375" },
  { iso2: "AD", country: "Andorra", callingCode: "+376" },
  { iso2: "MC", country: "Monaco", callingCode: "+377" },
  { iso2: "SM", country: "San Marino", callingCode: "+378" },
  { iso2: "VA", country: "Vatican City", callingCode: "+379" },
  { iso2: "UA", country: "Ukraine", callingCode: "+380" },
  { iso2: "RS", country: "Serbia", callingCode: "+381" },
  { iso2: "ME", country: "Montenegro", callingCode: "+382" },
  { iso2: "HR", country: "Croatia", callingCode: "+385" },
  { iso2: "SI", country: "Slovenia", callingCode: "+386" },
  { iso2: "BA", country: "Bosnia and Herzegovina", callingCode: "+387" },
  { iso2: "MK", country: "North Macedonia", callingCode: "+389" },
  { iso2: "CZ", country: "Czechia", callingCode: "+420" },
  { iso2: "SK", country: "Slovakia", callingCode: "+421" },
  { iso2: "LI", country: "Liechtenstein", callingCode: "+423" },

  { iso2: "IL", country: "Israel", callingCode: "+972" },
  { iso2: "AE", country: "United Arab Emirates", callingCode: "+971" },
  { iso2: "SA", country: "Saudi Arabia", callingCode: "+966" },
  { iso2: "QA", country: "Qatar", callingCode: "+974" },
  { iso2: "KW", country: "Kuwait", callingCode: "+965" },
  { iso2: "BH", country: "Bahrain", callingCode: "+973" },
  { iso2: "OM", country: "Oman", callingCode: "+968" },
  { iso2: "YE", country: "Yemen", callingCode: "+967" },
  { iso2: "JO", country: "Jordan", callingCode: "+962" },
  { iso2: "LB", country: "Lebanon", callingCode: "+961" },
  { iso2: "SY", country: "Syria", callingCode: "+963" },
  { iso2: "IQ", country: "Iraq", callingCode: "+964" },
];
